### ISSUE TITLE
Combine the Country and Subdivisions in one?

### ISSUE THREAD

**Issue by omar2205** [CodingGarden/flags#20]
Put the governorate logo on top of the country like this:
![image](https://user-images.githubusercontent.com/1373867/202004007-5d682311-c44d-4780-9bfd-800b585e691a.png)

**Comment by omar2205** [comment]
or even this 
![image](https://user-images.githubusercontent.com/1373867/202004320-8c3079d1-6e9b-4a3d-b34e-43f1e882cbed.png)

**Comment by w3cj** [comment]
I like the idea, but I think this will take up too much space. Hope you understand. With love and respect, -CJ.
